import type { Metadata } from 'next';
import TrpcClientProvider from '#components/providers/TrpcClient';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TrpcClientProvider>
          <main>{children}</main>
        </TrpcClientProvider>
      </body>
    </html>
  );
}
